CREATE DATABASE [Fast]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Fast', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.PROD\MSSQL\DATA\Fast.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Fast_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.PROD\MSSQL\DATA\Fast_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Fast] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [Fast] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Fast] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Fast] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Fast] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Fast] SET ARITHABORT OFF 
GO
ALTER DATABASE [Fast] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Fast] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Fast] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Fast] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Fast] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Fast] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Fast] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Fast] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Fast] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Fast] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Fast] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Fast] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Fast] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Fast] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Fast] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Fast] SET  READ_WRITE 
GO
ALTER DATABASE [Fast] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Fast] SET  MULTI_USER 
GO
ALTER DATABASE [Fast] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Fast] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Fast] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Fast] COLLATE Latin1_General_100_CI_AS_SC_UTF8
GO
USE [Fast]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [Fast]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Fast] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
